### ISSUE TITLE
Too many free variables for terms?

### ISSUE THREAD

**Issue by alexarice** [ericfinster/catt.io#11]
There is the following code to determine the free variables of terms:
```
and tm_free_vars t =
  match t with
  | VarT id -> SS.singleton id
  | DefAppT (_, args) ->
     List.fold_right SS.union (List.map tm_free_vars args) SS.empty
  | CellAppT (cell, args) -> 
     let args_fvs = List.fold_right SS.union (List.map tm_free_vars args) SS.empty in
     SS.union (cell_free_vars cell) args_fvs
```
It seems very odd that `(cell_free_vars cell)` is added to the free variables. This gives for example:
```
Simple normal form: [coh (x0 : *) : x0 -> x0](x)
Free variables x x0
```
whereas intuitively I feel the free variables should just be `x`?

Apologies if I have misunderstood how this is meant to work, I couldn't find a bit in the paper explaining how to calculate the free variables of coherences.

**Comment by ericfinster** [comment]
Yes, you are right.  I thought I had already noticed this bug and fixed it at some point, but clearly it's still around.  I pushed a fix.
