### ISSUE TITLE
PPX extension

### ISSUE THREAD

**Issue by jamievicary** [ericfinster/catt.io#6]
Eric suggested we could use a PPX syntax extension to allow us to write Catt terms directly in OCaml. This would remove the need for a separate parser, and give us an ability to work more flexibly (build lists of contexts, call other files, etc). It would also let us experiment with the Catt library interactively in the toplevel.

**Comment by jamievicary** [comment]
A half-way-house would be to have the possibility of parsing a .catt file and finishing with the cursor in a toplevel, so one can then interactively start to apply functions to the structures produced by the parser. If this would be trivial to do, it would be good to do it immediately, as I think it would already be useful.

**Comment by ericfinster** [comment]
see the recent changes
