### ISSUE TITLE
Ambiguity in definition of identities

### ISSUE THREAD

**Issue by alexarice** [ericfinster/catt.io#9]
the identity on a zero cell can be defined in two possible ways

```
let id = coh (x : *) : x -> x

let id2 = comp (x : *) : x -> x
```

@jamievicary seemed to believe that each term should either be a comp or a coh. Is it possible that the second term should not be accepted?

**Comment by ericfinster** [comment]
Right, the second term should not be accepted.  The boundary of the pasting diagram (x : *) should be the empty context so that the second one is not well typed.  This should be pretty easy to fix.

**Comment by alexarice** [comment]
I could take a look tomorrow if you want

**Comment by alexarice** [comment]
The arXiv version of the catt paper states that the boundary of (x : *) is (x : *) and not the empty context. This seems to agree with the definition of boundary on globular sums

**Comment by ericfinster** [comment]
I think we only define the boundary for k >= 0, in which case this is correct.  But in the case you point out, we should actually be calculating the -1-boundary (1 less than the dimension of the pasting diagram), in which case empty is the correct answer.  I just pushed a fix.
